### ISSUE TITLE
commit 1336453f65: IE <= 8 && Date.now() 

### ISSUE THREAD

**Issue by labdidi** [blueimp/jQuery-File-Upload#1258]
When i tried to upload some items with the IE7 or IE8, i got the error:

```
       Details:
       User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET CLR 1.1.4322; .NET4.0C) Timestamp: Wed, 2 May 2012 13:31:22 UTC
       Message: Object does not support this property or method.
       Line: 188
       Character: 13
       Code: 0
       URI: https://........../tools/jQueryFileUpload/js/jquery.fileupload.js
```

When i checked it , i found that the IExplorer <= 8 doesn' t support the method "Date.now()" !
For the Engines which have not been updated to support this method can work around the absence of this method using the following shim:
    if (!Date.now) {  
      Date.now = function now() {  
        return +(new Date);  
      };  
    }  

See => https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Date/now
