### ISSUE TITLE
jquery.fileupload.js is requiring jquery.ui.widget.js

### ISSUE THREAD

**Issue by fourcolors** [blueimp/jQuery-File-Upload#1764]
Hi

Im using requirejs first off, but I have included the jquery.fiileuplaod file and I get 

```
GET http://localhost:3000/assets/jquery.ui.widget.js 404 (Not Found) 
```

I don't think there should be a dependency on this file. I thought the only dependency is jquery. 

My shim looks like this

``` yml
  'jquery-plugins/jquery.fileupload': 
    deps: ['jquery']
    exports: '$.fileupload'
```
