### ISSUE TITLE
Not able to get individual progress of file

### ISSUE THREAD

**Issue by PoojaG20** [blueimp/jQuery-File-Upload#3545]
In my case I have multiple files to be uploaded at same time, but for progress and progressall, I am getting single value for total of size of files. lease help on what to do to get individual file progress.

**Comment by blueimp** [comment]
I've created a basic example using individual progress events, please let me know if this helps:

[JSFiddle](https://jsfiddle.net/kxom8jr0/)

Included scripts:
- https://blueimp.github.io/jQuery-File-Upload/js/vendor/jquery.ui.widget.js
- https://blueimp.github.io/jQuery-File-Upload/js/jquery.fileupload.js

HTML
```html
<input
  id="fileupload"
  type="file"
  name="files[]"
  data-url="//jquery-file-upload.appspot.com/"
  multiple>
```

CSS:
```css
.file {
   position: relative;
   background: linear-gradient(to right, lightblue 50%, transparent 50%);
   background-size: 200% 100%;
   background-position: right bottom;
   transition:all 1s ease;
}
 .file.done {
   background: lightgreen;
}
 .file a {
   display: block;
   position: relative;
   padding: 5px;
   color: black;
}
```

JS:
```js
$("#fileupload").fileupload({
  dataType: "json",
  add: function(e, data) {
    data.context = $('<p class="file">')
      .append($('<a target="_blank">').text(data.files[0].name))
      .appendTo(document.body);
    data.submit();
  },
  progress: function(e, data) {
    var progress = parseInt((data.loaded / data.total) * 100, 10);
    data.context.css("background-position-x", 100 - progress + "%");
  },
  done: function(e, data) {
    data.context
      .addClass("done")
      .find("a")
      .prop("href", data.result.files[0].url);
  }
});
```
